# Koyeb configuration
# Reference: https://www.koyeb.com/docs/reference/yaml-configuration

name: ecopulse

services:
  - name: backend
    type: service
    instance_type: nano
    region: fra
    ports:
      - port: 3000
        protocol: http
    env:
      - key: DATABASE_URL
        value: "{{ .env.DATABASE_URL }}"
      - key: PORT
        value: "3000"
    build:
      type: docker
    deploy:
      type: git
      repository: https://github.com/jondumad/EcoPulse-Backend
